config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "main#index"

  resources :articles do
    get :feed, on: :collection, defaults: { format: :xml }
    resources :likes, only: :create do
      collection do
        delete :destroy
      end
    end
  end
  resource :contact, only: %i[show create]
  resource :session, only: %i[new create destroy]
  resource :about, only: :show

  namespace :admin do
    resource :dashboard, only: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId

  has_one_attached :feature_image
  has_rich_text :content

  has_many :likes, dependent: :destroy
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags, inverse_of: :articles

  friendly_id :title, use: :slugged

  validates :title, presence: true

  with_options if: :published? do
    validates :summary, :content, presence: true
    validates :summary, length: { minimum: 150, maximum: 450 }
  end

  scope :published, -> { where.not(published_at: nil) }
  scope :unpublished, -> { where(published_at: nil) }

  def published
    published_at.present?
  end
  alias_method :published?, :published

  def tag_names
    tags.map(&:name)
  end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :email, :message, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article, touch: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags, inverse_of: :tags

  normalizes :name, with: ->(name) { name.strip.downcase }
  validates :name, presence: true, uniqueness: true
end

app/models/trix_pre_processor.rb
class TrixPreProcessor
  def initialize(content)
    @content = content
  end

  def process
    insert_code_blocks
  end

  private

  def insert_code_blocks
    @content.gsub(/<pre>(?:(?!<code>)([\s\S]*?))<\/pre>/, '<pre><code>\1</code></pre>')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  normalizes :email, with: ->(email) { email.strip.downcase }
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show; end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  def show
    @articles = Article.unpublished
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern

  include Pagy::Backend

  private

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in." unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def authenticate_user_from_session
    return unless session[:user_id]

    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end

  def set_anonymous_user_id
    unless cookies[:uuid]
      salt = Rails.application.credentials[:ip_hash_salt]
      raise unless salt

      value = Digest::SHA256.hexdigest("#{request.ip}#{salt}")
      cookies[:uuid] = { value: value, expires: 1.month.from_now, httponly: true }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_anonymous_user_id, only: :show

  def show
    articles = user_signed_in? ? Article : Article.published
    @article = articles.friendly.find(params[:id])

    fresh_when @article
  end

  def index
    @pagy, @articles = pagy_countless(Article.includes(:likes).published.order(published_at: :desc))

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def feed
    @articles = Article.includes(:tags).published.order(published_at: :desc).first(10)

    if stale?(last_modified: @articles.maximum(:updated_at), etag: @articles, public: true)
      respond_to do |format|
        format.xml { render layout: false, formats: [:rss] }
      end
    end
  end

  def new
    @article_form = ArticleForm.new
  end

  def create
    @article_form = ArticleForm.new(article_params)

    if @article_form.save
      redirect_to article_path(@article_form.article), notice: "Article has been created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article_form = ArticleForm.new(id: params[:id])
  end

  def update
    @article_form = ArticleForm.new(id: params[:id], **article_params)
    if @article_form.save
      redirect_to article_path(@article_form.article), notice: "Article has been updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.unpublished.friendly.find(params[:id])

    if @article.destroy
      redirect_to admin_dashboard_path, notice: "Article deleted"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :sub_title, :summary, :content, :published, :feature_image, tag_names: [])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      ContactMailer
        .with(
          name: @contact.name,
          email: @contact.email,
          message: @contact.message,
        )
        .contact_message
        .deliver_later

      redirect_to contact_path, notice: "Your message has been sent."
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_anonymous_user_id
  before_action :load_article

  def create
    Like.create!(uuid: cookies[:uuid], article: @article)
  end

  def destroy
    Like.find_by!(uuid: cookies[:uuid], article: @article).destroy!
  end

  private

  def load_article
    @article = Article.friendly.find(params[:article_id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @articles = Article.includes(:likes).published.order(published_at: :desc).first(4)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if (user = User.authenticate_by(email: params[:email], password: params[:password]))
      login user
      redirect_to root_path, notice: "You have been logged in"
    else
      flash[:alert] = "Incorrect email or password."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def og_keys
    %i[title description url image type]
  end
end

app/helpers/article_helper.rb
module ArticleHelper
  def social_image(article)
    if article.feature_image.present?
      rails_blob_url(article.feature_image.variant(resize_to_fit: [1200, 630]))
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/abouts/_header.html.erb
<div class="home-title">
  <div class="home-image-container">
    <%= image_tag "about_me_image.jpeg" %>
  </div>
  <div class="home-heading">
    <h1>Harry Venables</h1>
    <h3>Software Developer</h3>
  </div>
</div>

app/views/abouts/show.html.erb
<%= render "header" %>

<div class="about-container">
  <div class="about-me">
    <h3>About me</h3>
      <p>By day, you'll usually find me knee-deep in Ruby, happily wrangling code. But I’m always up for a little adventure into other programming languages—if it has syntax, I’m interested! Learning new languages and paradigms keeps me on my toes (and occasionally scratching my head).</p>
      <p>I call Taunton, in the beautiful southwest of the UK, home. When I’m not behind a screen, I’m either out riding the waves or wandering the countryside. Basically, if it’s outdoors, I’m in.</p>
    <h3>Background</h3>
     <p>I was born and raised in Wimbledon (I'm a big AFC wimbledon fan!).</p>
     <p>I originally studied International Business at Plymouth University. That allowed me to mix my studies with one of my main passions surfing. Once I graduated I moved back to London to work in advertising - working with large financial clients (I organised the advertising for the Oxford Cambridge boat race).</p>
     <p>In 2015, I decided that I wanted a change and studied web development at Makers Academy in London. Since then I have been working as a software developer and have been loving it!</p>
    <h3>Work Experience</h3>
      <p><b>2022-Present: Shopify</b> - Senior Software Engineer</p>
      <p><b>2019-2022: Immersive Labs</b> - Lead Backend Engineer</p>
      <p><b>2016-2019: Tagadab</b> - Software Engineer</p>
      <p><b>2014-2016: AML</b> - Production Executive</p>
    <h3>Favourite Languages to work with</h3>
    <div>
      <%= image_tag "ruby-logo.png", data: { title: "Ruby" }, alt: "Ruby Logo", title: "Ruby" %>
      <%= image_tag "elixir-logo.png", data: { title: "Elixir" }, alt: "Elixir Logo", title: "Elixir"  %>
      <%= image_tag "rust-logo.png", data: { title: "Rust" }, alt: "Rust Logo", title: "Rust"  %>
      <%= image_tag "js-logo.png", data: { title: "JavaScript" }, alt: "JavaScript Logo", title: "JavaScript"  %>
      <%= image_tag "elm-logo.png", data: { title: "Elm" }, alt: "Elm Logo", title: "Elm"  %>
    </div>
  </div>
</div>

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <% if blob.content_type == Mime[:gif].to_s %>
      <%= image_tag blob.representation(loader: { n: -1 }, resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
    <% else %>
      <%= image_tag url_for(blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])) %>
    <% end %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/dashboards/show.html.erb
<div class="actions">
  <%= link_to "New Article", new_article_path, class: 'btn' %>
  <%= button_to "Log out", session_path, method: :delete, class: 'btn' %>
</div>

<hr>

<h2>Unpublished Articles</h2>
<div class="articles-container">
  <% if @articles.any? %>
    <% @articles.each do |article| %>
      <%= render 'articles/article', article: article %>
    <% end %>
  <% else %>
    <h2>No Articles</h2>
  <% end %>
</div>

app/views/application/_form_error.html.erb
<% if form.object.errors[attribute].present? %>
  <div class="error-message" data-controller="error" data-error-target="message">
    <%= "Your #{attribute} #{form.object.errors[attribute].to_sentence}." %>
    <span class="error-close" data-action="click->error#close">&times;</span>
  </div>
<% end %>

app/views/articles/_article.html.erb
<article class="article-card">
  <%= link_to article_path(article), class: "title link" do %>
    <h3 class="heading">
      <%= article.title %>
    </h3>
  <% end %>
  <h5 class="heading sub-title">
    <%= article.sub_title %>
  </h5>
  <p class="summary">
  <%= article.summary.truncate(450) %>
  </p>
  <div class="footer">
    <%= link_to article_path(article), class: "read-more" do %>
      Read more <i class="fa-solid fa-arrow-right"></i>
    <% end %>
    <span>
      <%= pluralize(article.likes.size, "Like") %>
    </span>
  </div>
</article>

app/views/articles/_form.html.erb
<%= form_with model: article_form, id: "article-form", autocomplete: "off" do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= render "form_error", form: f, attribute: :title %>
  </div>
  <div class="field">
    <%= f.label :feature_image %>
    <%= f.file_field :feature_image %>
    <%= render "form_error", form: f, attribute: :feature_image %>
  </div>
  <div class="field">
    <%= f.label :sub_title %>
    <%= f.text_field :sub_title %>
    <%= render "form_error", form: f, attribute: :sub_title %>
  </div>
  <div class="field" data-controller="character-counter">
    <%= f.label :summary do %>
      <div class="article-summary-label">
        <span>Summary</span>
        <span>
          <strong data-character-counter-target="counter">---</strong><strong>/450</strong>
        </span>
      </div>
    <% end %>
    <%= f.text_area :summary, rows: 5, maxlength: 450, data: { "character-counter-target": "input" } %>
    <%= render "form_error", form: f, attribute: :summary %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.rich_text_area :content %>
    <%= render "form_error", form: f, attribute: :content %>
  </div>
  <div class="field">
    <%= f.label :published, 'Publish', class: 'checkbox-label' %>
    <%= f.check_box :published %>
    <%= render "form_error", form: f, attribute: :published %>
  </div>
  <div class="choices-field">
    <%= f.label :tag_names, "Tags" %>
    <%= f.select :tag_names, options_for_select(Tag.all.map(&:name), f.object.tag_names), {}, { multiple: true, id: "choose-tags" } %>
    <%= render "form_error", form: f, attribute: :tag_names %>
  </div>
  <div class="submit">
    <%= f.submit button_text, class: "btn" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render "form", article_form: @article_form, button_text: "Update article" %>

app/views/articles/index.html.erb
<div id="articles" class="articles-container">
  <% if @articles.any? %>
    <%= render partial: 'article', collection: @articles %>
  <% else %>
    <h2>No Articles</h2>
  <% end %>
</div>

<% if @pagy.next.present? %>
  <div id="next_link" class="more-articles">
    <%= link_to "More Articles", pagy_url_for(@pagy, @pagy.next), class: "btn", data: { turbo_stream: true } %>
  </div>
<% end %>

app/views/articles/index.turbo_stream.erb
<%= turbo_stream.append "articles" do %>
  <%= render partial: "article", collection: @articles %>
<% end %>

<%= turbo_stream.update "next_link" do %>
  <% if @pagy.next.present? %>
    <%= link_to "More Articles", pagy_url_for(@pagy, @pagy.next), class: "btn", data: { turbo_stream: true } %>
  <% end %>
<% end %>

app/views/articles/new.html.erb
<%= render "form", article_form: @article_form, button_text: "Create article" %>

app/views/articles/show.html.erb
<% content_for :title, @article.title %>
<% content_for :description, @article.summary %>
<% content_for :url, article_url(@article) %>
<% content_for :image, social_image(@article) %>
<% content_for :type, "article" %>

<div class="article-container">
  <div class="article-content">
    <h1><%= @article.title %></h1>
    <% if @article.sub_title %>
      <h3 class="sub_title"><%= @article.sub_title %></h3>
    <% end %>

    <div class="metadata">
      <div class="dates">
        <% if @article.published? %>
          <h5>Published: <%= @article.published_at.to_date.to_formatted_s(:long) %></h5>
          <% if @article.published_at.to_date < @article.updated_at.to_date %>
            <h5 class="edited">Edited: <%= @article.updated_at.to_date.to_formatted_s(:long) %></h5>
          <% end %>
        <% end %>
      </div>

      <div class="tags">
        <% @article.tags.each do |tag| %>
          <span class="tag"><%= tag.name.titlecase %></span>
        <% end %>
      </div>
    </div>

    <%= image_tag(@article.feature_image, class: "featured-image") if @article.feature_image.attached? %>

    <%= @article.content %>

    <%= turbo_frame_tag "article-likes" do %>
      <%= render "likes/like_article", article: @article %>
    <% end %>

    <% if user_signed_in? %>
      <br>
      <div class="actions">
        <%= link_to "Edit", edit_article_path(@article), class: "btn" %>
        <% unless @article.published? %>
          <%= button_to "Delete", article_path(@article), method: :delete, class: 'btn btn-danger', form: {data: {turbo_confirm: 'Are you sure you want to delete?'}} %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/_form.html.erb
<div class="contact-form">
  <%= form_with model: contact, url: contact_path, autocomplete: "off" do |f| %>
    <div class="field">
      <%= f.label :name, "Your name" %>
      <%= f.text_field :name %>
      <%= render "form_error", form: f, attribute: :name %>
    </div>
    <div class="field">
      <%= f.label :email, "Your email" %>
      <%= f.email_field :email %>
      <%= render "form_error", form: f, attribute: :email %>
    </div>
    <div class="field" data-controller="character-counter">
      <%= f.label :message do %>
        <div class="contact-message-label">
          <span>Message</span>
          <span>
            <strong data-character-counter-target="counter">---</strong><strong>/1000</strong>
          </span>
        </div>
      <% end %>
      <%= f.text_area :message, rows: 13, maxlength: 1000, data: { "character-counter-target": "input" } %>
      <%= render "form_error", form: f, attribute: :message %>
    </div>
    <div class="submit">
      <%= f.submit "Send message", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/contacts/show.html.erb
<div class="contact">
  <div id="taunton-map" style="width: 100%">
    <iframe width="500" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=Taunton+(My%20Business%20Name)&amp;t=&amp;z=12&amp;ie=UTF8&amp;iwloc=B&amp;output=embed">
      <a href="https://www.gps.ie/">gps trackers</a>
    </iframe>
  </div>
  <div class="contact-means">
    <div class="contact-icons">
      <div class="icon-container">
        <a href="https://x.com/HarryVenables" target="_blank">
          <i class="fa-brands fa-2x fa-twitter"></i>
        </a>
        <a href="https://github.com/hvenables" target="_blank">
          <i class="fa-brands fa-2x fa-github"></i>
        </a>
        <a href="https://www.linkedin.com/in/harry-venables-28109986" target="_blank">
          <i class="fa-brands fa-2x fa-linkedin"></i>
        </a>
      </div>
    </div>
    <%= render "form", contact: @contact %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="nav-container">
    <div class="logo">
      <%= link_to root_path do %>
        <h2>vena.codes</h2>
      <% end %>
    </div>
    <nav class="nav-links">
      <ul>
        <li>
          <%= link_to "Blog", articles_path %>
        </li>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "RSS", feed_articles_path %>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to "Admin", admin_dashboard_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_open_graph_meta.html.erb
<% og_keys.each do |key| %>
  <% if content_for(key) %>
    <meta name="og:<%= key %>" content="<%= content_for(key) %>">
  <% end %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "vena.codes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="description" content="<%= content_for(:description) || "A blog by Harry Venables a software developer, the blog primarily focuses on topics relating to programming and more specifically ruby." %>">

    <%= render "layouts/open_graph_meta" %>
    <link rel="preload" href="/fonts/FiraCode-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/fonts/FiraCode-Bold.woff2" as="font" type="font/woff2" crossorigin>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">

    <%= favicon_link_tag 'favicon.ico' %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"
    />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/333069cdb7.js" crossorigin="anonymous" defer></script>
  </head>
  <body id="app">
    <%= render "layouts/header" %>
    <div class="content">
      <div class="left-gutter"></div>
      <div class="main-area">
        <% flash.each do |type, message| %>
          <div data-controller="flash" data-flash-target="message" class="flash-message <%= type %>">
            <span><%= message %></span>
            <span data-action="click->flash#hide" class="flash-close">×</span>
          </div>
        <% end %>
        <%= yield %>
      </div>
      <div class="right-gutter"></div>
    </div>
    <footer>
      <a href="https://x.com/HarryVenables" target="_blank">
        <i class="fa-brands fa-2x fa-twitter"></i>
      </a>
      <a href="https://github.com/hvenables" target="_blank">
        <i class="fa-brands fa-2x fa-github"></i>
      </a>
      <a href="https://www.linkedin.com/in/harry-venables-28109986" target="_blank">
        <i class="fa-brands fa-2x fa-linkedin"></i>
      </a>
    </footer>
  </body>
</html>

app/views/likes/_like_article.html.erb
<div class="like-container">
  <span>
    <span class="like-count"><%= article.likes.count %></span>
    <% if article.likes.exists?(uuid: cookies[:uuid]) %>
      <%= button_to article_likes_path(article), method: :delete, class: "like" do %>
        <i class="fa-solid fa-heart fa-2xl"></i>
      <% end %>
    <% else %>
      <%= button_to article_likes_path(article), class: "like" do %>
        <i class="fa-regular fa-heart fa-2xl"></i>
      <% end %>
    <% end %>
  </span>
</div>

app/views/likes/create.html.erb
<%= turbo_frame_tag "article-likes" do %>
  <%= render "like_article", article: @article %>
<% end %>

app/views/likes/destroy.html.erb
<%= turbo_frame_tag "article-likes" do %>
  <%= render "like_article", article: @article %>
<% end %>

app/views/main/index.html.erb
<%= render 'abouts/header' %>

<div class="about-contact">
  <div class="about">
    <h2>About me</h2>
    <p>By day, you'll usually find me knee-deep in Ruby, happily wrangling code. But I’m always up for a little adventure into other programming languages—if it has syntax, I’m interested! Learning new languages and paradigms keeps me on my toes (and occasionally scratching my head).</p>
    <p>I call Taunton, in the beautiful southwest of the UK, home. When I’m not behind a screen, I’m either out riding the waves or wandering the countryside. Basically, if it’s outdoors, I’m in.</p>
    <%= link_to about_path, class: "read-more" do %>
        Read more <i class="fa-solid fa-arrow-right"></i>
    <% end %>
  </div>
  <div class="home-contact">
    <h2>Find me here</h2>
    <div class="home-icon-container">
      <a href="https://x.com/HarryVenables" target="_blank">
        <i class="fa-brands fa-2x fa-twitter"></i>
        <span>Twitter</span>
      </a>
      <a href="https://github.com/hvenables" target="_blank">
        <i class="fa-brands fa-2x fa-github"></i>
        <span>Github</span>
      </a>
      <a href="https://www.linkedin.com/in/harry-venables-28109986" target="_blank">
        <i class="fa-brands fa-2x fa-linkedin"></i>
        <span>Linkedin</span>
      </a>
    </div>
    <p>Want to say hi? Mail me at: <a href="mailto:harry@vena.codes" class="read-more">harry@vena.codes</a><p>
  </div>
</div>
<% if @articles.any? %>
  <br>
  <hr>
  <h2>Latest Articles</h2>
  <div class="articles-container">
      <% @articles.each do |article| %>
        <%= render 'articles/article', article: article %>
      <% end %>
  </div>
  <div class="more-articles">
    <%= link_to "More Articles", articles_path, class: "btn" %>
  </div>
<% end %>